name: Sentia Laboratory
favicon: null
layout_spectrum: 0.33395
typography_spectrum: 0.27928
title: Sentia Laboratory for the Developing Mind and Brain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71770908-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fb464a'
    - '#ffffff'
    - '#040404'
    - '#f59231'
    - '#c4c9cd'
  brandStrength: 0.375
  lightness: 0.5514527382329106
  saturation: 0.7832037291955203
  rhythmicContrast: 0.5
purpose: []
