name: Sentia Laboratory
favicon: null
layout_spectrum: 0.39611
typography_spectrum: 0.39495
title: Sentia Laboratory for the Neuroscience of Childhood
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d3ccb0'
    - '#b1a996'
    - '#8c652c'
    - '#f0f17c'
  brandStrength: 0.5
  lightness: 0.5514527382329106
  saturation: 0.7832037291955203
  rhythmicContrast: 0.6244636366609484
purpose: []
