name: Sentia Laboratory
favicon: null
layout_spectrum: 0.32442
typography_spectrum: 0.28664
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71770908-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fb464a'
    - '#ffffff'
    - '#040404'
    - '#f59231'
    - '#c4c9cd'
  brandStrength: 0.375
  lightness: 0.551452
  saturation: 0.783203
  rhythmicContrast: 0.25
purpose: []
