name: Sentia Laboratory
favicon: null
layout_spectrum: 0.89611
typography_spectrum: 0.27928
title: Sentia Laboratory for the Neuroscience of Childhood
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3198419401887804
  lightness: 0.5514527382329106
  saturation: 0.7832037291955203
  rhythmicContrast: 0.6244636366609484
purpose: []
