layout_spectrum: 0.26065593981184065
typography_spectrum: 0.6875347455497831
color:
  brandColors:
    - '#fb464a'
    - '#ffffff'
    - '#040404'
    - '#f59231'
    - '#c4c9cd'
  brandStrength: 0.25
  lightness: 0.551452
  saturation: 0.783203
  rhythmicContrast: 0.25
coverPrefs:
  filter: false
name: Sentia Laboratory
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71770908-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
