analytics:
  google: UA-71770908-1
color:
  brandColors:
    - '#fb464a'
    - '#ffffff'
    - '#040404'
    - '#f59231'
    - '#c4c9cd'
  brandStrength: 0.375
  lightness: 0.551452
  rhythmicContrast: 0.110197
  saturation: 0.783203
cta: {}
layout_spectrum: 0.709703
name: Sentia Laboratory
opengraph: {}
purpose: []
typography_spectrum: 0.6636
